# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc71c551d9e8655cf7f26f0ec4bb836ab8efda27561299754eb8cb36196c8de3b936af4c1cead3702d33272d5b8c1190c01cf0b72f1cfb5acb26dbf71ef3e615

test:
  secret_key_base: e90cfc253b34933bd356b578680f60e09f3cd716d56838772abe59e34620bf15b58211df2a72cc135a354d090668d919b08ce5869cb71ee98cd3db6a52682d4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
